config/routes.rb
Rails.application.routes.draw do
  resources :users do
    member do
      resources :reward_histories, only: [:index, :new, :create]
      delete 'reward_histories/:id', to: 'reward_histories#destroy', as: :delete_reward
    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reward_history.rb
class RewardHistory < ApplicationRecord
  belongs_to :giver, class_name: 'User', foreign_key: :given_by
  belongs_to :receiver, class_name: 'User', foreign_key: :given_to

  validates :points, numericality: { greater_than: 0, less_than_or_equal_to: 100 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reward_histories, foreign_key: :given_by, class_name: 'RewardHistory'
  has_many :received_rewards, foreign_key: :given_to, class_name: 'RewardHistory'

  validates :name, presence: true
  validates :p5_balance, :reward_balance, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reward_histories_controller.rb
class RewardHistoriesController < ApplicationController
  def index
    @user = User.find(params[:id])
    @rewards = @user.reward_histories
  end

  def new
    @user = User.find(params[:id])
    @users = User.where.not(id: @user.id)
  end

  def create
    giver = User.find(params[:id])
    receiver = User.find(params[:given_to])
    points = params[:points].to_i

    if giver.p5_balance >= points
      RewardHistory.transaction do
        giver.update!(p5_balance: giver.p5_balance - points)
        receiver.update!(reward_balance: receiver.reward_balance + points)
        RewardHistory.create!(given_by: giver.id, given_to: receiver.id, points: points)
      end
      redirect_to reward_histories_path(giver), notice: 'Reward given successfully!'
    else
      redirect_to new_reward_history_path(giver), alert: 'Insufficient P5 balance!'
    end
  end

  def destroy
    binding.pry
    reward = RewardHistory.find(params[:id])
    giver = reward.giver
    receiver = reward.receiver

    RewardHistory.transaction do
      giver.update!(p5_balance: giver.p5_balance + reward.points)
      receiver.update!(reward_balance: receiver.reward_balance - reward.points)
      reward.destroy!
    end
    redirect_to reward_histories_path(giver), notice: 'Transaction reversed successfully!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.p5_balance = 100
    @user.reward_balance = 0
    if @user.save
      redirect_to users_path, notice: 'User created successfully!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: 'User updated successfully!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reward_histories_helper.rb
module RewardHistoriesHelper
  def formatted_date(date)
    date.strftime("%m/%d/%Y")
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniPeerfives</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reward_histories/index.html.erb
<h1>Rewards for <%= @user.name %></h1>
<p>P5 Balance: <%= @user.p5_balance %></p>
<p>Reward Balance: <%= @user.reward_balance %></p>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Points</th>
      <th>Giver</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @rewards.each_with_index do |reward, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= formatted_date(reward.created_at) %></td>
        <td><%= reward.points %></td>
        <td><%= reward.giver.name %></td>
        <td>
          <%= link_to 'Delete', delete_reward_user_path(@user, reward), method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Reward', new_reward_history_path(@user) %>

app/views/reward_histories/new.html.erb
<h1>Give Reward</h1>

<% if flash[:alert] %>
  <p style="color: red;"><%= flash[:alert] %></p>
<% end %>

<%= form_with(url: reward_histories_path(@user), local: true) do |form| %>

  <div>
    <%= form.label :given_to, "Select Recipient" %>
    <%= form.select :given_to, options_from_collection_for_select(@users, :id, :name), prompt: 'Select a user' %>
  </div>

  <div>
    <%= form.label :points, "Enter Points to Give" %>
    <%= form.number_field :points, min: 1, max: [100, @user.p5_balance].min %>
    <p>Available P5 Balance: <%= @user.p5_balance %></p>
  </div>

  <div>
    <%= form.submit "Give Reward" %>
    <%= link_to 'Cancel', reward_histories_path(@user) %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>P5 Balance</th>
      <th>Reward Balance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= user.name %></td>
        <td><%= user.p5_balance %></td>
        <td><%= user.reward_balance %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user) %> |
          <%= link_to 'Rewards', reward_histories_path(user) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_with model: @user, local: true do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit 'Save' %>
  <%= link_to 'Cancel', users_path %>
<% end %>